name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: app-universal-debug.apk
          path: app/build/outputs/apk/debug/app-universal-debug.apk
